In [ ]:
Варіант 12:
Правило для заповнення квадратної матриці | Розмір матриць і векторів
       a_(ij)=(2j-0.5i)^(3)                        n = 4, m = 3    

In [11]:
import numpy as np

# a. Створити квадратну матрицю (n × n), заповнити її за правилом a_(ij)=(2j-0.5i)^(3)
n = 4
matrix_a = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        matrix_a[i, j] = (2 * (j + 1) - 0.5 * (i + 1)) ** 3

print("Matrix A:")
print(matrix_a)

# Знайти детермінант матриці
det_a = np.linalg.det(matrix_a)
print("\nDeterminant of matrix A:", det_a)

# Знайти обернену матрицю
if det_a != 0:
    inverse_a = np.linalg.inv(matrix_a)
    print("\nInverse of matrix A:")
    print(inverse_a)
else:
    print("\nMatrix A is singular and does not have an inverse.")

# b. Задати два вектори з n елементами, заповнені випадковими числами
vector_real = np.random.rand(n)  # Вектор з дійсними числами
vector_int = np.random.randint(1, 10, size=n)  # Вектор з цілими числами

print("\nVector with real numbers:", vector_real)
print("Vector with integer numbers:", vector_int)

# Обчислити їх суму і добуток
vector_sum = vector_real + vector_int
vector_dot_product = np.dot(vector_real, vector_int)

print("\nSum of vectors:", vector_sum)
print("Dot product of vectors:", vector_dot_product)

# c. Задати дві матриці, заповнені випадковими числами: одна розміру n × m, друга – m × n
m = 3
matrix_b = np.random.rand(n, m)
matrix_c = np.random.rand(m, n)

print("\nMatrix B (n x m):")
print(matrix_b)
print("\nMatrix C (m x n):")
print(matrix_c)

# Знайти їх добуток
matrix_product_bc = np.dot(matrix_b, matrix_c)

print("\nProduct of matrix B and matrix C:")
print(matrix_product_bc)

# d. Знайти добуток матриць і векторів (розбити на дві пари, для яких можливо виконання операції)
# Матриця A і вектор реал
matrix_vector_product1 = np.dot(matrix_a, vector_real)
print("\nProduct of matrix A and vector_real:")
print(matrix_vector_product1)

# Матриця C і вектор цілих чисел
matrix_vector_product2 = np.dot(matrix_c, vector_int)
print("\nProduct of matrix C and vector_int:")
print(matrix_vector_product2)


Matrix A:
[[3.37500e+00 4.28750e+01 1.66375e+02 4.21875e+02]
 [1.00000e+00 2.70000e+01 1.25000e+02 3.43000e+02]
 [1.25000e-01 1.56250e+01 9.11250e+01 2.74625e+02]
 [0.00000e+00 8.00000e+00 6.40000e+01 2.16000e+02]]

Determinant of matrix A: 1295.9999999999825

Inverse of matrix A:
[[ 2.         -6.69444444  7.55555556 -2.88194444]
 [-1.13888889  4.625      -6.25        2.82638889]
 [ 0.61111111 -2.5         3.5        -1.67361111]
 [-0.13888889  0.56944444 -0.80555556  0.39583333]]

Vector with real numbers: [0.5873539  0.53865605 0.14753284 0.21567305]
Vector with integer numbers: [2 8 9 3]

Sum of vectors: [2.5873539  8.53865605 9.14753284 3.21567305]
Dot product of vectors: 7.458770928318549

Matrix B (n x m):
[[0.05920965 0.92464293 0.51373321]
 [0.0966354  0.57909047 0.75034257]
 [0.88727148 0.77180958 0.46451382]
 [0.09084492 0.20989578 0.64610868]]

Matrix C (m x n):
[[0.22994495 0.1615891  0.72892884 0.79812882]
 [0.2069588  0.41162304 0.45825426 0.92070456]
 [0.57123984 0.5016

In [43]:
import pandas as pd

# a. Створити таблицю за описом
data = {
    'University Name': ['Київський національний університет', 'Львівська політехніка', 'Харківський національний університет',
        'Одеський національний університет', 'Дніпровський національний університет', 'Національний університет КПІ',
        'Чернівецький національний університет', 'Тернопільський національний університет', 'Полтавський технічний університет',
        'Вінницький національний технічний університет', 'Запорізький національний університет', 'Житомирський державний університет',
        'Сумський державний університет', 'Хмельницький національний університет', 'Ужгородський національний університет'],
    'City': ['Київ', 'Львів', 'Харків', 'Одеса', 'Дніпро', 'Київ', 'Чернівці', 'Тернопіль', 'Полтава', 'Вінниця', 'Запоріжжя', 'Житомир', 'Суми', 'Хмельницький', 'Ужгород'],
    'English Proficiency (%)': [75, 60, 55, 70, 45, 80, 40, 50, 35, 65, 42, 30, 50, 48, 38],
    'Recommendation Level': [8.5, 7.8, 7.0, 6.5, 7.1, 8.0, 6.8, 6.2, 5.9, 7.3, 6.7, 5.5, 6.9, 6.4, 5.8],
    'Graduate Employment Rate (%)': [60, 55, 50, 52, 48, 65, 42, 30, 35, 53, 45, 38, 55, 40, 36],
    'Average Salary (USD)': [30000, 25000, 24000, 22000, 21000, 32000, 19000, 18000, 17500, 26000, 20000, 16000, 19500, 17000, 18500]
}

# Створення DataFrame
df = pd.DataFrame(data)

# Виведення DataFrame
print("DataFrame:")
print(df)

# b. Знайти і вивести університети з рейтинговою оцінкою випускників вищою за 7.0
top_universities = df[df['Recommendation Level'] > 7.0][['University Name', 'Recommendation Level']]
print("\n\nUniversities with recommendation level higher than 7.0:")
print(top_universities)

# c. Знайти і вивести університети з рівнем володіння англійською мовою вищим 50%
proficient_universities = df[df['English Proficiency (%)'] > 50][['University Name', 'English Proficiency (%)']]
print("\n\nUniversities with English proficiency higher than 50%:")
print(proficient_universities)

# d. Визначити університет з найвищим відсотком випускників-розробників
highest_developer_university = df[df['Graduate Employment Rate (%)'] == df['Graduate Employment Rate (%)'].max()]['University Name'].values[0]
print("\n\nUniversity with the highest percentage of graduates working in R&D:")
print(highest_developer_university)

# e. Знайти і вивести університети, рівень заробітної плати випускників яких нижчий за середній з рейтингу
average_salary = df['Average Salary (USD)'].mean()
below_average_salary_universities = df[df['Average Salary (USD)'] < average_salary][['University Name', 'Average Salary (USD)']]
print("\n\nUniversities with average salary lower than the overall average:")
print(below_average_salary_universities)

# f. Визначити скільки університетів з кожного міста у рейтингу
city_counts = df['City'].value_counts()
print("\n\nNumber of universities from each city in the ranking:")
print(city_counts)

DataFrame:
                                  University Name          City  \
0              Київський національний університет          Київ   
1                           Львівська політехніка         Львів   
2            Харківський національний університет        Харків   
3               Одеський національний університет         Одеса   
4           Дніпровський національний університет        Дніпро   
5                    Національний університет КПІ          Київ   
6           Чернівецький національний університет      Чернівці   
7         Тернопільський національний університет     Тернопіль   
8               Полтавський технічний університет       Полтава   
9   Вінницький національний технічний університет       Вінниця   
10           Запорізький національний університет     Запоріжжя   
11             Житомирський державний університет       Житомир   
12                 Сумський державний університет          Суми   
13          Хмельницький національний університет  